name: Imagen Docker Prueba Tecnica

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  #contents: write

  security-events: write

  actions: read
  contents: read
jobs:
  publicar-hello-nginx-docker-imagen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build y Push'
        run: |
          docker build . --tag ghcr.io/manuelsysadmin/imagendockerpruebatecnica:latest
          docker push ghcr.io/manuelsysadmin/imagendockerpruebatecnica:latest

  docker-scout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: 'Login Docker'
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Docker Scout CVEs
      uses: docker/scout-action@v0.18.1
      with:
        command: cves
        image: "ghcr.io/manuelsysadmin/imagendockerpruebatecnica:latest" # If image is not set (or empty) the most recently built image, if any, will be used instead.
        sarif-file: sarif.output.json
        only-fixed: true
        only-severities: critical,high
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment
        exit-code: true
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      if: ${{ github.event_name != 'pull_request' }}
      with:
        image-ref: ${{ env.DOCKERHUB_SLUG }}:latest          
        exit-code: '1'
        ignore-unfixed: true
        scan-type: image
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        format: 'sarif'
        output: 'scan-results-latest.sarif'
            
    - name: Upload SARIF result
      id: UPLOAD_SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.output.json
        category: my-analysis-tool
