name: Imagen Docker Prueba Tecnica

on:
  push:
    branches:
      - main
  workflow_dispatch:

  
jobs:
  checkov:
    permissions:
      contents: read
      security-events: write
    uses: ManuelSysAdmin/pruebatecnica/blob/main/.github/workflows/checkov.yaml@main 
  publicar-hello-nginx-docker-imagen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build y Push'
        run: |
          docker build . --tag ghcr.io/manuelsysadmin/imagendockerpruebatecnica:latest
          docker push ghcr.io/manuelsysadmin/imagendockerpruebatecnica:latest
